version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 80:3000
    networks:
      - web_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  web_network:
    external: true
