import type { Metadata } from 'next'
import localFont from 'next/font/local'
import React from 'react'

import './globals.css'

import { ReactQueryProvider, UseCaseContextProvider } from 'common/di'
import { MenuLayoutView } from 'presenter/menu/view'
import Loading from './loading'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'NextJS Clean Architecture',
  description: 'Generated by pk911',
  icons: { icon: '/favicon.ico' },
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ko' className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className={'h-screen overflow-hidden'}>
        <ReactQueryProvider>
          <UseCaseContextProvider>
            <MenuLayoutView>{children}</MenuLayoutView>
            <Loading />
          </UseCaseContextProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
